name: 🚀 Deploy DEV websites
on:
    workflow_dispatch:
    push:
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files to root site
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftpdevhost }}
        username: ${{ secrets.ftpdevusername }}
        password: ${{ secrets.ftpdevpassword }}
        server-dir: httpdocs/
        local-dir: ./web/

    - name: 📂 Sync files to sub folder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftpdevhost }}
        username: ${{ secrets.ftpdevusername }}
        password: ${{ secrets.ftpdevpassword }}
        server-dir: httpdocs/hlstatsx/
        local-dir: ./web/
