name: test

on:
  release:
    types:
      - created
      - edited
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Zip Folder
        run: zip -r default-hlstatsx-files-${{github.ref_name}}.zip default
    
